name: Tests

on: push

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 15]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
        env:
          CI: false

      - run: yarn test

      - run: yarn build
